# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [2]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [5]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['2' 'top' '2' 'top' '4.5' 'bottom' 'top' 'top' '4.5' '4.5']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [12]:
print(*np.random.choice(range(1, 10), size=1))

9


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [14]:
print(np.random.choice(range(1, 10), size=(4, 6)))

[[3 8 6 9 4 2]
 [1 5 1 6 4 9]
 [7 4 8 2 5 5]
 [4 5 5 3 3 5]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [5]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[3 1 4 2 1 4 1 1 0 4]


Згенеруйте одну випадкову цифру.

In [15]:
print(np.random.randint(1, 9, 1))

[4]


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [16]:
print(np.random.randint(10, 99, (4, 5)))

[[91 11 82 21 86]
 [32 28 44 93 65]
 [26 32 59 43 31]
 [30 43 12 55 33]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.3369603119037976


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [18]:
print(np.random.sample((3, 4)))

[[0.78890062 0.88167109 0.50091417 0.16739428]
 [0.34541789 0.93021366 0.01477286 0.06103725]
 [0.94602783 0.27193863 0.13757228 0.12272514]]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [20]:
a = 3
b = 5

In [23]:
(b - a) * np.random.sample((1, 10))

array([[0.98291775, 0.62167231, 0.92700436, 1.91487644, 1.49176291,
        0.8557379 , 1.09051759, 1.42753666, 1.79844954, 1.61594199]])

### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[9 5 3 7 8 1 0 2 6 4]


Перетасуйте матрицю $M$.

In [24]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [55]:
# Місце для Вашого коду

np.random.shuffle(M)
M
# tmpM = np.array(M.flat)
# np.random.shuffle(tmpM)
# tmpM.reshape((4, 5))

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9]])

## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [15]:
np.random.seed(42)

In [16]:
print(np.random.randint(10))

6


In [17]:
print(np.random.randint(10))

3


In [18]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [19]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [51]:
np.random.seed(None)
p = 0.5
n = 10
tosses = np.random.choice(["Head","Tail"], p = [p, 1 - p], size = n)
print(tosses)

['Tail' 'Head' 'Tail' 'Head' 'Head' 'Head' 'Tail' 'Tail' 'Head' 'Tail']


In [52]:
heads = list(tosses).count("Head")
tails = list(tosses).count("Tail")

print("{} heads and {} tails".format(heads,tails))

5 heads and 5 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [74]:
prob = 0.5
newTosses = np.random.choice(["Head", "Tail"], p = (prob, 1 - prob), size = 100)
h = list(newTosses).count("Head")
t = list(newTosses).count("Tail")

print(f"head: {h}, tails: {t}")

head: 52, tails: 48


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [104]:
againNewTosses = np.random.randint(low=0, high=2, size=100)
h = list(againNewTosses).count(0)
t = list(againNewTosses).count(1)

print(f"head: {h}, tails: {t}")

head: 49, tails: 51


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [171]:
againTosses = np.round(np.random.sample(100))
print(againTosses)
h = list(againTosses).count(1)
t = list(againTosses).count(0)

print(f"head: {h}, tails: {t}")

[0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1.
 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1.
 1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.
 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0.
 1. 0. 0. 0.]
head: 54, tails: 46


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [209]:
amts = (10,50,100,250,500,1000,2500,5000,10000)
for n in amts:
    againTosses = np.round(np.random.sample(n))
#     print(againTosses)
    h = list(againTosses).count(1)
    t = list(againTosses).count(0)
    print(f"n: {n}, empiric prob: {h / n}")

n: 10, empiric prob: 0.6
n: 50, empiric prob: 0.4
n: 100, empiric prob: 0.42
n: 250, empiric prob: 0.504
n: 500, empiric prob: 0.522
n: 1000, empiric prob: 0.509
n: 2500, empiric prob: 0.5
n: 5000, empiric prob: 0.501
n: 10000, empiric prob: 0.5052


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [221]:
n = 60
data = list(np.random.choice(range(1, 7), n))
# print(data)
amt = np.array([data.count(p) for p in range(1, 7)])
probs = np.round(list(amt / n), 2)
print(amt)
print(probs)

[ 8 11 15 10  8  8]
[0.13 0.18 0.25 0.17 0.13 0.13]


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [224]:
amt = (10,50,100,250,500,1000,2500,5000,10000)
for n in amt:
    data = list(np.random.choice(range(1, 7), n))
    # print(data)
    amt = np.array([data.count(p) for p in range(1, 7)])
    probs = np.round(list(amt / n), 2)
    print(f"probs: {list(probs)}")


probs: [0.0, 0.2, 0.3, 0.3, 0.1, 0.1]
probs: [0.14, 0.1, 0.18, 0.14, 0.16, 0.28]
probs: [0.14, 0.14, 0.21, 0.16, 0.13, 0.22]
probs: [0.16, 0.16, 0.18, 0.14, 0.18, 0.18]
probs: [0.16, 0.18, 0.19, 0.18, 0.15, 0.15]
probs: [0.16, 0.18, 0.16, 0.17, 0.15, 0.18]
probs: [0.19, 0.17, 0.16, 0.16, 0.15, 0.17]
probs: [0.17, 0.16, 0.17, 0.17, 0.16, 0.18]
probs: [0.17, 0.17, 0.17, 0.16, 0.17, 0.17]


## 5 Колода карт
### 5.1 Реалізація

In [231]:
# Визначимо номінали, масті та карти
Ranks = {'2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('7', '♡'), ('7', '♠'), ('7', '♣'), ('7', '♢'), ('K', '♡'), ('K', '♠'), ('K', '♣'), ('K', '♢'), ('A', '♡'), ('A', '♠'), ('A', '♣'), ('A', '♢'), ('8', '♡'), ('8', '♠'), ('8', '♣'), ('8', '♢'), ('9', '♡'), ('9', '♠'), ('9', '♣'), ('9', '♢'), ('10', '♡'), ('10', '♠'), ('10', '♣'), ('10', '♢'), ('2', '♡'), ('2', '♠'), ('2', '♣'), ('2', '♢'), ('3', '♡'), ('3', '♠'), ('3', '♣'), ('3', '♢'), ('Q', '♡'), ('Q', '♠'), ('Q', '♣'), ('Q', '♢'), ('6', '♡'), ('6', '♠'), ('6', '♣'), ('6', '♢'), ('5', '♡'), ('5', '♠'), ('5', '♣'), ('5', '♢'), ('J', '♡'), ('J', '♠'), ('J', '♣'), ('J', '♢'), ('4', '♡'), ('4', '♠'), ('4', '♣'), ('4', '♢')]


In [232]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

7♡, 7♠, 7♣, 7♢, K♡, K♠, K♣, K♢, A♡, A♠, A♣, A♢, 8♡, 8♠, 8♣, 8♢, 9♡, 9♠, 9♣, 9♢, 10♡, 10♠, 10♣, 10♢, 2♡, 2♠, 2♣, 2♢, 3♡, 3♠, 3♣, 3♢, Q♡, Q♠, Q♣, Q♢, 6♡, 6♠, 6♣, 6♢, 5♡, 5♠, 5♣, 5♢, J♡, J♠, J♣, J♢, 4♡, 4♠, 4♣, 4♢


In [233]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♡7, ♡K, ♡A, ♡8, ♡9, ♡10, ♡2, ♡3, ♡Q, ♡6, ♡5, ♡J, ♡4
♠7, ♠K, ♠A, ♠8, ♠9, ♠10, ♠2, ♠3, ♠Q, ♠6, ♠5, ♠J, ♠4
♣7, ♣K, ♣A, ♣8, ♣9, ♣10, ♣2, ♣3, ♣Q, ♣6, ♣5, ♣J, ♣4
♢7, ♢K, ♢A, ♢8, ♢9, ♢10, ♢2, ♢3, ♢Q, ♢6, ♢5, ♢J, ♢4


In [234]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('K', '♡'), ('3', '♡'), ('3', '♣'), ('Q', '♡'), ('J', '♣'), ('4', '♣'), ('7', '♠'), ('Q', '♢'), ('4', '♢'), ('J', '♡'), ('K', '♠'), ('Q', '♠'), ('3', '♢'), ('7', '♡'), ('8', '♣'), ('2', '♣'), ('5', '♠'), ('2', '♡'), ('J', '♢'), ('10', '♡'), ('2', '♢'), ('A', '♠'), ('5', '♣'), ('3', '♠'), ('A', '♢'), ('Q', '♣'), ('6', '♢'), ('8', '♢'), ('8', '♠'), ('7', '♣'), ('K', '♣'), ('5', '♢'), ('4', '♠'), ('6', '♣'), ('9', '♠'), ('10', '♣'), ('9', '♣'), ('A', '♡'), ('10', '♠'), ('7', '♢'), ('J', '♠'), ('9', '♡'), ('6', '♡'), ('8', '♡'), ('A', '♣'), ('4', '♡'), ('5', '♡'), ('9', '♢'), ('K', '♢'), ('10', '♢'), ('2', '♠'), ('6', '♠')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [238]:
amts = (10, 50, 100, 250, 500, 1000, 2500, 5000, 10000)
results = []
for n in amts:
    sample = [Cards[np.random.randint(len(Cards))] for i in range(n)]
    count = 0
    for i in range(len(sample)):
        if sample[i][0] in ('2', '4', '6', '8', '10'):
            count += 1
    results.append(count / n)
print(results)
print(5/13)

[0.5, 0.36, 0.42, 0.392, 0.424, 0.395, 0.388, 0.3856, 0.3754]
0.38461538461538464


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [35]:
# Місце для Вашого коду



### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [36]:
# Місце для Вашого коду

